import type { Produto } from "./types"

export const produtos: Produto[] = [
  {
    id: "1",
    nome: "Água Mineral 500ml",
    descricao: "Água mineral sem gás em garrafa de 500ml.",
    preco: 2.5,
    categoria: "Alimentos e Bebidas",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "2",
    nome: "Pão Francês",
    descricao: "Pão francês fresco, vendido por unidade.",
    preco: 0.75,
    categoria: "Alimentos e Bebidas",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "3",
    nome: "Sabonete Líquido",
    descricao: "Sabonete líquido hidratante para as mãos, 250ml.",
    preco: 12.9,
    categoria: "Higiene e Cuidados Pessoais",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "4",
    nome: "Detergente Multiuso",
    descricao: "Detergente multiuso para limpeza geral, 500ml.",
    preco: 8.5,
    categoria: "Limpeza",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "5",
    nome: "Analgésico",
    descricao: "Analgésico para dores de cabeça e musculares, 20 comprimidos.",
    preco: 15.9,
    categoria: "Farmácia e Bem-estar",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "6",
    nome: "Refrigerante Cola 2L",
    descricao: "Refrigerante sabor cola em garrafa de 2 litros.",
    preco: 9.9,
    categoria: "Alimentos e Bebidas",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "7",
    nome: "Papel Higiênico",
    descricao: "Pacote com 4 rolos de papel higiênico folha dupla.",
    preco: 12.5,
    categoria: "Higiene e Cuidados Pessoais",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "8",
    nome: "Desinfetante",
    descricao: "Desinfetante para banheiro e áreas gerais, 1L.",
    preco: 10.9,
    categoria: "Limpeza",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "9",
    nome: "Vitamina C",
    descricao: "Suplemento de Vitamina C, 30 comprimidos.",
    preco: 25.9,
    categoria: "Farmácia e Bem-estar",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: false,
  },
  {
    id: "10",
    nome: "Leite Integral 1L",
    descricao: "Leite integral em embalagem de 1 litro.",
    preco: 5.9,
    categoria: "Alimentos e Bebidas",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "11",
    nome: "Shampoo",
    descricao: "Shampoo para todos os tipos de cabelo, 350ml.",
    preco: 18.9,
    categoria: "Higiene e Cuidados Pessoais",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
  {
    id: "12",
    nome: "Sabão em Pó",
    descricao: "Sabão em pó para roupas, embalagem de 1kg.",
    preco: 15.9,
    categoria: "Limpeza",
    imagem: "/placeholder.svg?height=300&width=300",
    disponivel: true,
  },
]
